### ISSUE TITLE
paquete npm

### ISSUE THREAD

**Issue by geopamplona** [agustinbouillet/numero-telefono-argentino#25]
Hola, 

Estaría muy bien sacar un paquete npm con toda la funcionalidad para que sea fácilmente importable a proyectos react.

Estoy probando importarla desde react el fichero de la carpeta dist y me da algún error

Un saludo!

**Comment by agustinbouillet** [comment]
¡Gracias por la sugerencia @geopamplona ! Es un feature que vendría muy bien. Estuve con poco tiempo ultimamente. Tal vez la semana que viene me haga un rato y arme el paquete. 

¡¡Gracias!! 🙏
